[package]
name = "blockchain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "0.3.34"
serde = "1.0"
serde_derive = "1.0.197"
serde_json = "1.0.114"
sha2 = "0.10.8"